from building import *
import rtconfig
cwd     = GetCurrentDir()
src = []
src     += Glob('*.c')
CPPPATH = [cwd]
LOCAL_CCFLAGS = ''
group = DefineGroup('Drivers', src, depend = ['BSP_USING_USER_DMA_CONFIG'], CPPPATH = CPPPATH, LOCAL_CCFLAGS = LOCAL_CCFLAGS)


Return('group')
