#ifndef _LIZ_LOG_CFG_H_
#define _LIZ_LOG_CFG_H_

#define LIZ_APP_HEARTBEAT_DEBUG 
#define LIZ_APP_SPECTRUM_DEBUG
#define LIZ_APP_WEATHER_DEBUG
#define LIZ_BSP_DEBUG
// #define LIZ_BSP_IMU_DEBUG
#define LIZ_BSP_ADCFFT_DEBUG
#define LIZ_NET_MQTT_DEBUG
#define LIZ_SYS_APPCONTROLLER_DEBUG
#define LIZ_APP_DEBUG

#endif
